### ISSUE TITLE
Converting values to ºC and mm automatically?

### ISSUE THREAD

**Issue by Pakillo** [VeruGHub/easyclimate#29]
Some users might be confused that values are in ºC*100 and mm*100 for temperature and precipitation, respectively. Shall we return the values already in ºC and mm? Obviously the conversion it's very easy to do within the function.

The only disadvantage I can think of right now is increased memory use if you want to save a lot of these data... But in those cases the users could always multiply by 100 to avoid floating values again? I think the majority of users will want to work with ºC and mm directly...

**Comment by VeruGHub** [comment]
I agree that returning the values in ºC and mm is easier for the user. And make things easy to others is the philosophy here...

**Comment by Pakillo** [comment]
Alright. Let's make the change then, to return values in ºC and mm. This change will break most tests, so we need to update them too (just dividing the values in the tests by 100, or multiplying by 0.01)
