### ISSUE TITLE
temporal and spatial extent

### ISSUE THREAD

**Issue by VeruGHub** [VeruGHub/easyclimate#30]
We need to update the temporal extent in the documentation: 
period - https://verughub.github.io/easyclimate/reference/get_daily_climate.html

@Pakillo just to be sure, do you know if the spatial extent has changed with the new update of the data base?

**Comment by Pakillo** [comment]
According to Christoph's document, the spatial extent has not changed

![image](https://user-images.githubusercontent.com/1597843/142781387-38bc14cc-00b3-4902-84af-1dc0703f5acf.png)
