### ISSUE TITLE
web updates

### ISSUE THREAD

**Issue by VeruGHub** [VeruGHub/easyclimate#31]
@Pakillo 
No se como cambiar en la web la sección de referencias. Aparece la documentación antigua asociada a get_daily_climate. He estado mirando un poco y parece que se especifican las funciones que aparecen en esta sección en los .ylm. He encontrado un pkgdown.ylm ignorado y otro _pkgdown.ylm vacio. No he querido tocar para no liarla... Los articles si que están acutualizados ¿Puedes echarlo un vistazo cuando tengas un rato?
También habría que actualizar la versión del paquete que sale en la web arriba a la izquierda y en "Releases" (¿no?)

**Comment by Pakillo** [comment]
ok, lo miro

**Comment by Pakillo** [comment]
Creo que ya está todo actualizado
