### ISSUE TITLE
Cleaner output

### ISSUE THREAD

**Issue by VeruGHub** [VeruGHub/easyclimate#34]
We could remove x/y or lat/lon columns when output="dataframe" since they have the same information

**Comment by Pakillo** [comment]
yeah that would be good. But we should be consistent with the output, that is, the output dataframe should always have two columns named "lon" and "lat", regardless if the input data is a matrix or data.frame. (Currently, if coords is a matrix, the output df has two columns named "x" & "y")

So I guess it's a matter of dropping x & y columns when input coords is a data.frame, and renaming x, y to lon,lat when input is a matrix. no?
