### ISSUE TITLE
removing repeated code

### ISSUE THREAD

**Issue by VeruGHub** [VeruGHub/easyclimate#49]
For consistency I am removing [this test](https://github.com/VeruGHub/easyclimate/blob/bc102832ce749a3aae7083c83d3a8ffeda7efeb5/R/get_daily_climate.R#L102) since it is tested again in [get_daily_climate_single](https://github.com/VeruGHub/easyclimate/blob/bc102832ce749a3aae7083c83d3a8ffeda7efeb5/R/get_daily_climate_single.R#L45) as other arguments.

**Comment by Pakillo** [comment]
ok!
